# Generated by Django 4.0.6 on 2022-11-09 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCode', models.CharField(max_length=20)),
                ('productPrice', models.DecimalField(decimal_places=5, max_digits=10)),
                ('productTitle', models.CharField(max_length=500)),
                ('productSize', models.CharField(max_length=100)),
                ('productDescription', models.TextField()),
                ('productImg1', models.ImageField(upload_to='')),
                ('productImg2', models.ImageField(upload_to='')),
                ('productImg3', models.ImageField(upload_to='')),
                ('productImg4', models.ImageField(upload_to='')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
