# Generated by Django 4.0.6 on 2022-11-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_product_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImg1',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
    ]
