# Generated by Django 4.0.6 on 2022-11-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_productimg1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImg2',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productImg3',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productImg4',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
    ]
