# Generated by Django 4.0.6 on 2022-11-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryImg',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
