# Generated by Django 4.0.6 on 2022-11-11 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_rename_categoryimg1_category_categoryimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryImg',
            new_name='categoryImg2',
        ),
    ]
