# Generated by Django 4.0.6 on 2022-11-11 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0005_rename_categoryimg_category_categoryimg2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryImg2',
            new_name='categoryImg',
        ),
    ]
