# Generated by Django 4.0.6 on 2022-11-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0006_rename_categoryimg2_category_categoryimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryImg',
            field=models.ImageField(upload_to='uploads/categories/'),
        ),
    ]
